# This prevents testing branches that are created just for PRs
branches:
  only:
  - master

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system
  - gem install bundler

sudo: false
language: ruby
cache: bundler

script:
  - bundle update
  - bundle exec rake pedant
env:
  global:
    - "PEDANT_OPTS=\"--skip-oc_id\""

matrix:
  include:
    - rvm: 2.4.1
      env: PEDANT_KNIFE_TESTS=true PEDANT_ALLOW_RVM=1
    - rvm: 2.4.1
      env: SINGLE_ORG=true
    - rvm: 2.4.1
      env: CHEF_FS=true
# Commented out until we work with a released version again
#    - rvm: 2.2.5
#      env:
#        - CHEF_FS=true
#        - "GEMFILE_MOD=\"gem 'chef', github: 'chef/chef'\""
#    - rvm: 2.3.1
#      env:
#        - CHEF_FS=true
#        - "GEMFILE_MOD=\"gem 'chef', github: 'chef/chef'\""
    - rvm: 2.4.1
      env: FILE_STORE=true
    - rvm: 2.4.1
      script: bundle exec rake chef_spec
      env: TEST=chef_spec
    - rvm: 2.3.3
      script: bundle exec rake spec
      env: TEST=rake_spec
    - rvm: 2.4.1
      script: bundle exec rake spec
      env: TEST=rake_spec
    - rvm: 2.4.1
      script: bundle exec rake style
      env: TEST=chefstyle
