rvm: 2.0
gemfile: Gemfile

# This prevents testing branches that are created just for PRs
branches:
  only:
  - master


sudo: false
script: bundle exec rake pedant

matrix:
  include:
    - rvm: 2.0
    - rvm: 2.1
    - rvm: 2.1
      env: PEDANT_KNIFE_TESTS=true
    - rvm: 2.1
      env: SINGLE_ORG=true
    - rvm: 2.1
      env: CHEF_FS=true
    - rvm: 2.1
      env: FILE_STORE=true
    - rvm: 2.1
      script: bundle exec rake chef_spec
      env: TEST=chef_spec
    - rvm: 2.1
      script: bundle exec rake spec
      env: TEST=rake_spec

  allow_failures:
    - rvm: 2.1
      gemfile: gemfiles/latest-chef.gemfile
      script: bundle exec rake chef_spec
      enc: TEST=chef_spec_latest
#    - rvm: 2.1.1
#      gemfile: gemfiles/berkshelf.gemfile
#      script: bundle exec rake berkshelf_spec
