rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
script: bundle exec rake spec
matrix:
  allow_failures:
    - rvm: 1.8.7           # We support 1.8.7, but chef-pedant doesn't
    - rvm: 2.0.0           # chef-pedant has at least one failure in 2.0.0
    - rvm: jruby-19mode    # Mixlib Shellout uses fork+exec
