rvm: 1.9.3

gemfile: Gemfile

script: bundle exec rake spec

matrix:
  include:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.8.7
      env: SKIP_PEDANT=true
      gemfile: gemfiles/no-pedant.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/latest-pedant.gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: jruby-19mode
      env: SKIP_PEDANT=true
      gemfile: gemfiles/no-pedant.gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.1
      gemfile: Gemfile
  allow_failures:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/latest-pedant.gemfile
